### ISSUE TITLE
This plugin should use "ResourceDirectory" to find its script files

### ISSUE THREAD

**Issue by M-Reimer** [FireFlyVDR/vdr-plugin-burn#1]
yaVDR uses a patch to make the scripts, that are exclusively used by the burn-plugin:

- vdrburn-archive.sh
- vdrburn-dvd.sh

easier to move out of $PATH which should not be spoiled with special scripts only used internally by one software.

BUT the proper way to fix this would actually be to use the "ResourceDirectory" which is supported by VDR since quite a while and is meant to be used for such "resource stuff" like special scripts.

**Comment by FireFlyVDR** [comment]
I don't think that scripts are resource files. Also Wikipedia describes Resource Files as files not involved in the program flow (which leaves pictures, audio files etc). BTW is the burn plugin using the ResourceDirectory() since 2016 for e.g. its background pictures and audio silence file. Due to the nature of the scripts and the rarely usage of DVDs nowadays I'll keep it as it is.
